/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.ConverteMoeda;
import classes.conexao;
import static classes.conexao.statement;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jbars.Barcode;

/**
 *
 * @author aluno
 */
public class TelaMercado extends javax.swing.JFrame {

    /**
     * Creates new form TelaMercado
     */
    public TelaMercado() {
        initComponents();
    }
    String dbData, dbHora,linha;
    int seq=0;
    double tota=0.00,to=0.00,Tatal=0.00,recebidos=0.00;
    Date dataHora = new Date();
    conexao comb = new conexao();
    Calendar now = Calendar.getInstance();
    Timer timer = new Timer(1000, new dataHora());
    ConverteMoeda cm = new ConverteMoeda();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        lblogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbatendente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paineldetexto = new javax.swing.JPanel();
        paineldetexto1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lbpreco = new javax.swing.JLabel();
        lbvalor = new javax.swing.JLabel();
        txtqtde = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtabela = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txttroco = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtrecebido = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbimgprod = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lbcodigobarras = new javax.swing.JLabel();
        lbnomeproduto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbhora = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbdata = new javax.swing.JLabel();
        lbpapel = new javax.swing.JPanel();
        lbcupom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 160, 150));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 240, -1));
        getContentPane().add(lbatendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 130, 130));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LITTLE_GUI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, 90, 20));

        paineldetexto.setBackground(new java.awt.Color(51, 51, 51));
        paineldetexto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paineldetextoLayout = new javax.swing.GroupLayout(paineldetexto);
        paineldetexto.setLayout(paineldetextoLayout);
        paineldetextoLayout.setHorizontalGroup(
            paineldetextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        paineldetextoLayout.setVerticalGroup(
            paineldetextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(paineldetexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 230, 240));

        paineldetexto1.setBackground(new java.awt.Color(153, 153, 153));
        paineldetexto1.setForeground(new java.awt.Color(255, 255, 255));

        lb1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Preço:");

        lb2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("Qtde:");

        lb3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb3.setText("Valor:");

        lbpreco.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbpreco.setForeground(new java.awt.Color(255, 255, 255));
        lbpreco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbvalor.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbvalor.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtqtde.setText("1");
        txtqtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paineldetexto1Layout = new javax.swing.GroupLayout(paineldetexto1);
        paineldetexto1.setLayout(paineldetexto1Layout);
        paineldetexto1Layout.setHorizontalGroup(
            paineldetexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineldetexto1Layout.createSequentialGroup()
                .addGroup(paineldetexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paineldetexto1Layout.createSequentialGroup()
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbpreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paineldetexto1Layout.createSequentialGroup()
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txtqtde, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paineldetexto1Layout.createSequentialGroup()
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbvalor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        paineldetexto1Layout.setVerticalGroup(
            paineldetexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineldetexto1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(paineldetexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1)
                    .addComponent(lbpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(paineldetexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb2)
                    .addComponent(txtqtde, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(paineldetexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb3)
                    .addComponent(lbvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(paineldetexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 230, 240));

        tbtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço", "Quantidade", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbtabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 460, 230));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RECEBIDO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        txttroco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txttroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 110, -1));

        txttotal.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 110, -1));

        txtrecebido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtrecebido.setText(" 0,00");
        txtrecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecebidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtrecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 110, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("F5 - Altera Quantidade     F1 - Finaliza Compra    ESC - Encerra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 460, 30));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 110, 20));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TROCO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 110, 20));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 110, 20));
        getContentPane().add(lbimgprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 220));

        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoKeyReleased(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 30));
        getContentPane().add(lbcodigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 190, 50));

        lbnomeproduto.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbnomeproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbnomeproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 180, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 250, 20));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        lbhora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 110, 30));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        lbdata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbdata, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbdata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, 30));

        javax.swing.GroupLayout lbpapelLayout = new javax.swing.GroupLayout(lbpapel);
        lbpapel.setLayout(lbpapelLayout);
        lbpapelLayout.setHorizontalGroup(
            lbpapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbcupom, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        lbpapelLayout.setVerticalGroup(
            lbpapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbcupom, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        getContentPane().add(lbpapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 250, 320));

        setSize(new java.awt.Dimension(1111, 702));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        { ImageIcon imagem = new  ImageIcon(TelaMercado.class.getResource("/img/lllo.png"));    
    Image imag = imagem.getImage().getScaledInstance(lblogo.getWidth(), lblogo.getHeight(), Image.SCALE_DEFAULT);
    lblogo.setIcon(new ImageIcon(imag));
    }
        { ImageIcon imagem = new  ImageIcon(TelaMercado.class.getResource("/img/atendente.jfif"));
    Image imag = imagem.getImage().getScaledInstance(lblogo.getWidth(), lbatendente.getHeight(), Image.SCALE_DEFAULT);
    lbatendente.setIcon(new ImageIcon(imag));
        }
        
        Date dataHora = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbdata.setText(dt.format(dataHora));
 
        Timer timer = new Timer(1000, new dataHora());
        timer.start();
        txtqtde.setEditable(false);
         txtrecebido.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyReleased
       
        if (txtcodigo.getText().length() == 13)
        {
               evt.setKeyCode(KeyEvent.VK_ENTER);
       
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) 
        {
        pegaFoto();
        CarregaDados();
        carregaBarCode();
        txtcodigo.setText("");
        tota=tota+(Tatal);
        txttotal.setText(cm.ConvMoeda(String.valueOf(tota)));
       
        
        }
        
        }
         
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) 
        {  
            JOptionPane sair = new JOptionPane();
            
            int Sair = sair.showConfirmDialog(null,"CONFIRME PARA ENCERRAR O CAIXA","Sair",JOptionPane.YES_NO_OPTION);
            
            if(Sair == JOptionPane.YES_OPTION)
            {
                 System.exit(0);           
            }  
        }
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F5) 
        {  
                 txtcodigo.setEnabled(false);
                 txtqtde.setEditable(true);
                 txtqtde.setText("");
                 txtqtde.requestFocus();
                 
                 
                 }  
               
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F1) 
        {  
            if  (txtrecebido.getText().equals ("R$ 0,00"))
            
                 txtcodigo.setEnabled(false);
            txtrecebido.setEnabled(true);
                  txtrecebido.setText("");
                 txtrecebido.requestFocus(); 
        }  
                       
               
    }//GEN-LAST:event_txtcodigoKeyReleased

    private void txtqtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdeActionPerformed
        txtcodigo.setEnabled(true);
        txtcodigo.requestFocus();
    }//GEN-LAST:event_txtqtdeActionPerformed

    private void txtrecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecebidoActionPerformed
         recebidos=Double.parseDouble(txtrecebido.getText()) - tota;
                    JOptionPane sair = new JOptionPane();
            
            int Sair = sair.showConfirmDialog(null,"CONFIRME PARA FINALIZAR A COMPRA","Compra",JOptionPane.YES_NO_OPTION);
            
            if(Sair == JOptionPane.YES_OPTION)
            {
                JOptionPane.showMessageDialog (null, recebidos);
                 txttroco.setText(cm.ConvMoeda(String.valueOf(recebidos)));
                 pegaCupom();
                 gravaBanco();
                 geraSenha();
            }  
        
             
    }//GEN-LAST:event_txtrecebidoActionPerformed
    class dataHora implements ActionListener 
         {
           @Override
           public void actionPerformed(ActionEvent ae) 
          {
             Calendar now = Calendar.getInstance();
             lbhora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
          }
       }
 private void geraSenha() {

        lbpapel.setVisible(true);
        lbcupom.setText("<html><br><p style='font-size:5px;"
                + "<center>"
                + "text-align:center'>=======================</p><br><p "
                + "text-align:center'><h3>CUPOM BIG           </h3></p><br><p "
                + "text-align:center'>Av.Prof.Lucas Nogueira Garçes,200</p><br><p "
                + "text-align:center'>ATIBAIA - SP</p><br><p "
                + "text-align:center'>=======================</p><br><p "
                + "text-align:center'>Cupom Fiscal  Numero:"+seq+"</p><br><p "
                + "text-align:center'> "+lbdata.getText()+" - "+lbhora.getText()+"</p><br><p "
                + "text-align:center'>=======================</p><br><p "
                        + "text-align:center'> "+linha+"</p><br><p "
                + "text-align:center'>=======================</p><br><p "
                + "text-align:>COMPRA: "+txttotal.getText()+"</p><br><p "      
                + "text-align:>RECEBIDO: "+txtrecebido.getText()+"</p><br><p "    
                + "text-align:>TROCO: "+txttroco.getText()+"</p><br><p "      
                + "text-align:center'>=======================</p><br><p " 
                + "text-align:center'>OBRIGADO PELA PREFERENCIA</p><br><p "    
                + "</ceneter>"        
                + "</p><html>");
        lbpapel.add(lbcupom);
        movimento();
    }
        public void movimento()
    {
     lbpapel.setVisible(true);
        new Thread()
        {
            public void run()
            { 
                int y = 220;
                int x = 710;
                
                while(true){
                    if(x < 100){
                        x++;
                        lbpapel.setLocation(y,x);
                    
                        }
                    try{
                        sleep(6);
                    }catch (Exception e)
                    {
                    }
                }
            }            
        }.start();
    }
             

        
        private void pegaCupom() {
        
         String sql = "Select max(tb03_nro_cupom) from tb03_cupom";
         
            
        try{

         int maxSenha = 0;
      
                
        conexao objetoBD = new conexao();
          
        
             seq = 0;
        objetoBD.conectar(); 
        ResultSet rs = statement.executeQuery(sql);  
       
        while (rs.next()) 
        {
             maxSenha = rs.getInt(1);
        }
        
        seq = maxSenha + 1; 
        
        
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
        
             private void gravaBanco()
    {
           SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        dbData = dt.format(dataHora);
        
        String sql = "INSERT INTO tb03_cupom VALUES (";
              sql+="'"+ seq + "'," + txttotal + ",'" +lbdata.getText()+ "')";
               
              
        try{

        comb.conectar();
        
       int qtdreg = conexao.runSQL(sql);

        comb.desconectar();
        
        }
        catch (Exception e){
             System.out.println(e.getMessage());
        }
    }
    
     

        
    private void pegaFoto(){

 { ImageIcon imagem = new  ImageIcon(TelaMercado.class.getResource("/img/"+txtcodigo.getText()+".jpg"));
        
    Image imag = imagem.getImage().getScaledInstance(lbimgprod.getWidth(), lbimgprod.getHeight(), Image.SCALE_DEFAULT);
        
    lbimgprod.setIcon(new ImageIcon(imag));
    }


}
      private void carregaBarCode()
    {
        float altura = 47;
        int fonteSize = 14;
        
        Image imagem;
        imagem = Barcode.createImage(Barcode.TYPE_CODE128,txtcodigo.getText(), altura, Font.SERIF, fonteSize,true, Barcode.ALIGN_CENTER,Font.ITALIC,Color.BLACK, Color.BLACK, 0);
        imagem = Barcode.createImage(Barcode.TYPE_CODE128,txtcodigo.getText(), altura, Font.DIALOG, fonteSize, true, Barcode.ALIGN_CENTER,Font.BOLD,Color.BLACK, Color.BLACK, 0);
        lbcodigobarras.setIcon(new ImageIcon(imagem)); 
    }
    private void CarregaDados(){
        String sql="select * from tb01_produtos where tb01_cod_prod= "+txtcodigo.getText();
        System.out.println(sql);
                DefaultTableModel tab = (DefaultTableModel) tbtabela.getModel();
                try {
                    comb.conectar();
                    ResultSet rs=comb.selectSQL(sql);                    
                    if(rs.next()){
                        
                        Tatal=((rs.getDouble("tb01_preco")*Integer.parseInt(txtqtde.getText())));
                       
                        lbpreco.setText(cm.ConvMoeda(rs.getString("tb01_preco")));
                        lbvalor.setText(cm.ConvMoeda(String.valueOf(rs.getDouble("tb01_preco")*Integer.parseInt(txtqtde.getText()))));
                        tab.addRow(new Object[]{rs.getString("tb01_descricao"), cm.ConvMoeda(rs.getString("tb01_preco")),   
                            txtqtde.getText(), cm.ConvMoeda(String.valueOf(rs.getDouble("tb01_preco")*Integer.parseInt(txtqtde.getText())))}); 
                     String   nomeProd=rs.getString("tb01_descricao");
                        
                           
                              linha+="<p style='font-size:8px; text-align:left'><a>" +nomeProd.substring(0, nomeProd.length())+"</a></p>";
            linha+="<p style='font-size:6px; color:black;'>"+lbpreco.getText()+" x "+txtqtde.getText()+" = "+lbvalor.getText()+"</p>";
                        
                        tbtabela.setModel(tab); 
                    }
                    comb.desconectar();
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(TelaMercado.class.getName()).log(Level.SEVERE, null, ex);
                }
             
    }

 
    /**
     * @param args the command line arguments
     */
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lbatendente;
    private javax.swing.JLabel lbcodigobarras;
    private javax.swing.JLabel lbcupom;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel lbimgprod;
    private javax.swing.JLabel lblogo;
    private javax.swing.JLabel lbnomeproduto;
    private javax.swing.JPanel lbpapel;
    private javax.swing.JLabel lbpreco;
    private javax.swing.JLabel lbvalor;
    private javax.swing.JPanel paineldetexto;
    private javax.swing.JPanel paineldetexto1;
    private javax.swing.JTable tbtabela;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtqtde;
    private javax.swing.JTextField txtrecebido;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttroco;
    // End of variables declaration//GEN-END:variables
}
